from main import CUENTA_BANCARIA

OBJETO_CUENTA_BANCARIA = CUENTA_BANCARIA("Juan Pérez", 2000)

print(OBJETO_CUENTA_BANCARIA.info(0))

OBJETO_CUENTA_BANCARIA.DEPOSITAR()

print(OBJETO_CUENTA_BANCARIA.info(0))

OBJETO_CUENTA_BANCARIA.RETIRAR()

print(OBJETO_CUENTA_BANCARIA.info(0))




